RoomReservation/Models/Room.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace RoomReservation.Models
{
    public class Room
    {
        [Key]
        [DatabaseGenerated( DatabaseGeneratedOption.Identity )]
        public int RoomId { get; set; }
        public string RoomNo { get; set; }
        public string RoomType { get; set; }
        public decimal Rate { get; set; }
        public string RoomStatus { get; set; }
    }
}

RoomReservation/Controllers/RoomBookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RoomReservation.Models;
using RoomReservation.Services;
using RoomReservation.ViewModel;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace RoomReservation.Controllers
{
    public class RoomBookingController : Controller
    {
        private IReservationData _reservationData;

        public RoomBookingController( IReservationData reservationData)
        {
            _reservationData = reservationData;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult BookRoom(int roomId,decimal roomRate, string roomNo, string roomType)
        {
            ViewBag.RoomId = roomId;
            ViewBag.RoomRate = roomRate;
            ViewBag.RoomNo = roomNo;
            ViewBag.RoomType = roomType;

            return View();
        }

        [HttpPost]
        public IActionResult BookRoom( RoomBoookingViewModel model )
        {
            var newRoomBooking = new RoomBooking();
            if (ModelState.IsValid)
            {
                newRoomBooking.RoomId = model.RoomId;
                newRoomBooking.BookingDateFrom = model.BookingDateFrom;
                newRoomBooking.BookingDateTo = model.BookingDateTo;
                newRoomBooking.BookingStatus = "Reserved";
                newRoomBooking.TotalBill = model.TotalBill;

                _reservationData.AddBooking( newRoomBooking );
            }
            return View();
        }
    }
}

RoomReservation/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RoomReservation.Models;
using RoomReservation.Services;
using RoomReservation.ViewModel;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace RoomReservation.Controllers
{
    public class RoomController : Controller
    {
        private IReservationData _reservationData;
        public RoomController( IReservationData reservationData )
        {
            _reservationData = reservationData;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            var rooms = new RoomViewModel();
            rooms.Rooms = _reservationData.GetRooms().ToList();

            return View( rooms );
        }

        [HttpGet]
        public IActionResult EditRoom( int roomId, string roomNo )
        {
            ViewData["RoomId"] = roomId;
            ViewData["RoomNo"] = roomNo;
            return View();
        }

        [HttpPost]
        public IActionResult EditRoom( RoomViewModel model )
        {
            Room room = new Room();
            if (ModelState.IsValid)
            {
                room.RoomId = model.RoomId;
                room.RoomNo = model.RoomNo;
                room.RoomType = model.RoomType;
                room.RoomStatus = "Available";
                room.Rate = model.Rate;

                _reservationData.UpdateRoom( room );
                return RedirectToAction( nameof( Index ) );
            }
            else
            {
                return View();
            }
        }

        //[HttpGet]
        //public IActionResult Details( int id, string roomNo )
        //{
        //    var roomBooking = new RoomBooking();
        //    ViewBag.RoomNo = roomNo;
        //    roomBooking = _reservationData.( id );
        //    return View( roomBooking );
        //}

    }
}

RoomReservation/Views/Room/Details.cshtml
@model RoomReservation.Models.RoomBooking

<div>Your Total Bill for Room : @ViewBag.RoomNo is <b>@Model.TotalBill</b></div>

<a asp-action="Index"><< Back To Rooms</a>

RoomReservation/Views/Room/EditRoom.cshtml
@model RoomReservation.ViewModel.RoomViewModel

<h1>Edit @ViewData["RoomNo"]</h1>

<form method="post">
    <input type="hidden" asp-for=@Model.RoomId value=@ViewData["RoomId"] />

    <div class="form-group">
        <label asp-for=@Model.RoomNo></label>
        <input asp-for=@Model.RoomNo value=@ViewData["RoomNo"] />
    </div>

    <div class="form-group">
        <label asp-for=@Model.RoomType>Room Type</label>
        <select asp-for="@Model.RoomType">
            <option value="Single">Single</option>
            <option value="Double">Double</option>
            <option value="Family">Family</option>
        </select>
    </div>

    <div class="form-group">
        <label asp-for=@Model.Rate></label>
        <input asp-for=@Model.Rate value=@ViewData["Rate"] />
    </div>

    <input class="btn btn-default" type="submit" name="Update" value="Update" />

</form>

RoomReservation/Views/Room/Index.cshtml
@model RoomReservation.ViewModel.RoomViewModel

<h1>Rooms</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Room No</th>
            <th>Room Type</th>
            <th>Rate</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var room in Model.Rooms)
        {
          @Html.Partial( "_Summary", room );
        }
    </tbody>
</table>

RoomReservation/Views/Room/_Summary.cshtml
@model RoomReservation.Models.Room

@if (Model.RoomStatus == "Available")
{
<tr class="success">
    <td>@Model.RoomNo</td>
    <td>@Model.RoomType</td>
    <td>@Model.Rate</td>
    <td>@Model.RoomStatus</td>
    
    <td>
        <a asp-controller="RoomBooking" asp-action="BookRoom"
           asp-route-roomId="@Model.RoomId"
           asp-route-roomRate="@Model.Rate" 
           asp-route-roomNo="@Model.RoomNo" 
           asp-route-roomType="@Model.RoomType">BOOK!</a>
    </td>
    
    <td>
        <a asp-controller="Room" asp-action="Details"
           asp-route-id="@Model.RoomId"
           asp-route-roomNo="@Model.RoomNo">Details</a>
    </td>
    
    <td>
        <a asp-controller="Room" asp-action="EditRoom"
           asp-route-roomId="@Model.RoomId"
           asp-route-roomNo="@Model.RoomNo">Edit Room</a>
    </td>
</tr>
}
else if (Model.RoomStatus == "Reserved")
{
    <tr class="danger">
        <td>@Model.RoomNo</td>
        <td>@Model.RoomType</td>
        <td>@Model.Rate</td>
        <td>@Model.RoomStatus</td>
        <td><a asp-controller="Room" asp-action="Details" 
               asp-route-id="@Model.RoomId" 
               asp-route-roomNo="@Model.RoomNo">Details</a></td>
    </tr>
}