RoomReservation/Models/ModalFooter.cs
namespace RoomReservation.Models
{
    public class ModalFooter
    {
        public string SubmitButtonText { get; set; } = "Submit";
        public string CancelButtonText { get; set; } = "Cancel";
        public string SubmitButtonID { get; set; } = "btn-submit";
        public string CancelButtonID { get; set; } = "btn-cancel";
        public bool OnlyCancelButton { get; set; }
    }
}

RoomReservation/Models/ModalHeader.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RoomReservation.Models
{
    public class ModalHeader
    {
        public string Heading { get; set; }
    }
}

RoomReservation/Controllers/ApplicationRoleController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RoomReservation.Data;
using RoomReservation.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace RoomReservation.Controllers
{
    public class ApplicationRoleController : Controller
    {
        private readonly RoleManager<ApplicationRole> roleManager;

        public ApplicationRoleController(RoleManager<ApplicationRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var model = new List<ApplicationRoleListViewModel>();
            model = roleManager.Roles.Select(r =>
                new ApplicationRoleListViewModel
                {
                    RoleName = r.Name,
                    Id = r.Id,
                    Description = r.Description
                }).ToList();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddEditApplicationRole(string id)
        {
            var model = new ApplicationRoleViewModel();
            var applicationRole = await roleManager.FindByIdAsync(id);
            if (applicationRole != null)
            {
                model.Id = applicationRole.Id;
                model.RoleName = applicationRole.Name;
                model.Description = applicationRole.Description;
            }

            return PartialView("_AddEditApplicationRole", model);
        }

        [HttpPost]
        public async Task<IActionResult> AddEditApplicationRole(string id, ApplicationRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var isExist = !string.IsNullOrEmpty(id);
                var applicationRole = isExist ? await roleManager.FindByIdAsync(id) : new ApplicationRole
                {
                    CreatedDate = DateTime.UtcNow
                };

                applicationRole.Name = model.RoleName;
                applicationRole.Description = model.Description;
                applicationRole.IpAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString();

                var roleResult = isExist
                    ? await roleManager.UpdateAsync(applicationRole)
                    : await roleManager.CreateAsync(applicationRole);
                if (roleResult.Succeeded)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteApplicationRole(string id)
        {
            var name = string.Empty;
            if (!string.IsNullOrEmpty(id))
            {
                var applicationRole = await this.roleManager.FindByIdAsync(id);
                if(applicationRole != null)
                {
                    name = applicationRole.Name;
                }
            }

            return PartialView("_DeleteApplicationRole", name);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteApplicationRole(string id, IFormCollection form)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var applicationRole = await roleManager.FindByIdAsync(id);
                if (applicationRole != null)
                {
                    IdentityResult roleResult = await roleManager.DeleteAsync(applicationRole);
                    if (roleResult.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }

            return View();
        }
    }
}

RoomReservation/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RoomReservation.Models;
using RoomReservation.Services;
using RoomReservation.ViewModel;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace RoomReservation.Controllers
{
    public class RoomController : Controller
    {
        private IReservationData _reservationData;
        public RoomController( IReservationData reservationData )
        {
            _reservationData = reservationData;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            var rooms = new RoomViewModel();
            rooms.Rooms = _reservationData.GetRooms().ToList();

            return View( rooms );
        }

        [HttpGet]
        public IActionResult EditRoom( int roomId, string roomNo )
        {
            ViewData["RoomId"] = roomId;
            ViewData["RoomNo"] = roomNo;
            return View();
        }

        [HttpPost]
        public IActionResult EditRoom( RoomViewModel model )
        {
            Room room = new Room();
            if (ModelState.IsValid)
            {
                room.RoomId = model.RoomId;
                room.RoomNo = model.RoomNo;
                room.RoomType = model.RoomType;
                room.RoomStatus = "Available";
                room.Rate = model.Rate;

                _reservationData.UpdateRoom( room );
                return RedirectToAction( nameof( Index ) );
            }
            else
            {
                return View();
            }
        }

        //[HttpGet]
        //public IActionResult Details( int id, string roomNo )
        //{
        //    var roomBooking = new RoomBooking();
        //    ViewBag.RoomNo = roomNo;
        //    roomBooking = _reservationData.( id );
        //    return View( roomBooking );
        //}

    }
}

RoomReservation/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RoomReservation.Data;
using RoomReservation.ViewModel;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace RoomReservation.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly RoleManager<ApplicationRole> roleManager;

        public UserController(UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var model = new List<UserListViewModel>();
            model = this.userManager.Users.Select(u => new UserListViewModel
            {
                Email = u.Email,
                Id = u.Id,
                Name = u.Name
            }).ToList();
            return View(model);
        }

        [HttpGet]
        public IActionResult AddUser()
        {
            var model = new UserViewModel
            {
                ApplicationRoles = this.roleManager.Roles.Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Id
                }).ToList()
            };

            return PartialView("_AddUser", model);
        }

        [HttpPost]
        public async Task<IActionResult> AddUser(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    Name = model.Name,
                    Email = model.Email,
                    UserName = model.UserName,
                    AccessFailedCount = 0,
                    EmailConfirmed = true,
                    LockoutEnabled = false,
                    PhoneNumberConfirmed = false,
                    TwoFactorEnabled = false
                };

                var result = await this.userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    var role = await this.roleManager.FindByIdAsync(model.ApplicationRoleId);
                    if(role != null)
                    {
                        var roleResult = await this.userManager.AddToRoleAsync(user, role.Name);
                        if (roleResult.Succeeded)
                        {
                            return RedirectToAction("Index");
                        }
                    }
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var model = new EditUserViewModel
            {
                ApplicationRoles = this.roleManager.Roles.Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Id
                }).ToList()
            };

            if (!string.IsNullOrEmpty(id))
            {
                var user = await this.userManager.FindByIdAsync(id);
                if (user != null)
                {
                    model.Name = user.Name;
                    model.Email = user.Email;
                    model.ApplicationRoleId = this.roleManager.Roles.Single(r => r.Name == userManager.GetRolesAsync(user).Result.Single()).Id;
                }
            }

            return PartialView("_EditUser", model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(string id, EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.FindByIdAsync(id);
                if (user != null)
                {
                    user.Name = model.Name;
                    user.Email = model.Email;
                    var existingRole = (await userManager.GetRolesAsync(user)).Single();
                    var existingRoleId = roleManager.Roles.Single(r => r.Name == existingRole).Id;
                    var result = await userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        if (existingRoleId != model.ApplicationRoleId)
                        {
                            var roleResult = await userManager.RemoveFromRoleAsync(user, existingRole);
                            if (roleResult.Succeeded)
                            {
                                var applicationRole = await roleManager.FindByIdAsync(model.ApplicationRoleId);
                                if (applicationRole != null)
                                {
                                    var newRoleResult = await userManager.AddToRoleAsync(user, applicationRole.Name);
                                    if (newRoleResult.Succeeded)
                                    {
                                        return RedirectToAction("Index");
                                    }
                                }
                            }
                        }
                    }
                }
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var name = string.Empty;
            if (!string.IsNullOrEmpty(id))
            {
                var applicationUser = await userManager.FindByIdAsync(id);
                if (applicationUser != null)
                {
                    name = applicationUser.Name;
                }
            }

            return PartialView("_DeleteUser", name);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id, FormCollection form)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var applicationUser = await userManager.FindByIdAsync(id);
                if (applicationUser != null)
                {
                    var result = await userManager.DeleteAsync(applicationUser);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }

            return View();
        }
    }
}

RoomReservation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="~/node_modules/jqueryui/jquery-ui.css" rel="stylesheet" />

    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>

    <script src="~/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>

    <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />

    <style>
        .carousel-inner > .item > img,
        .carousel-inner > .item > a > img {
            width: 70%;
            margin: auto;
        }
    </style>

    <script src="~/node_modules/jqueryui/jquery-ui.js"></script>

    <script>
        $(function () {
            $("#datepickerfr").datepicker();
            $("#datepickerto").datepicker();
        });

        function CalculateTotal() {
            var start = $("#datepickerfr").datepicker("getDate");
            var end = $("#datepickerto").datepicker("getDate");

            if (start != null && end != null) {
                days = (end - start) / (1000 * 60 * 60 * 24);
                $("#days").val(days);
                rate = $("#rate").val();
                total = days * rate;
                $("#total").val(total);
            }
            else {
                alert("Please check your inputs");
            }
        }

    </script>

</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">My Hotel</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="Room" asp-action="Index">Rooms</a></li>
                <li><a href="#">Manage Booking</a></li>
                <li><a href="#">About</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        User Management
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a asp-controller="ApplicationRole" asp-action="Index">Roles</a></li>
                        <li><a asp-controller="User" asp-action="Index">Users</a></li>
                        <li><a href="#">Page 1-3</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>

    <div>
        @RenderBody()
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

RoomReservation/Views/Shared/_Modal.cshtml
@model RoomReservation.Models.BootstrapModel
<div aria-hidden="true" aria-labelledby="@Model.AreaLabeledId" role="dialog" tabindex="-1" id="@Model.ID" class="modal fade">
    <div class="modal-dialog @Model.ModalSizeClass">
        <div class="modal-content">
        </div>
    </div>
</div>

RoomReservation/Views/Shared/_ModalFooter.cshtml
@model RoomReservation.Models.ModalFooter
<div class="modal-footer">
    <button data-dismiss="modal" id="@Model.CancelButtonID" class="btn btn-default" type="button">@Model.CancelButtonText</button>
    @if (!Model.OnlyCancelButton)
    {
        <button class="btn btn-success" id="@Model.SubmitButtonID" type="submit">
            @Model.SubmitButtonText
        </button>
    }
</div>

RoomReservation/Views/Shared/_ModalHeader.cshtml
@model RoomReservation.Models.ModalHeader
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">@Model.Heading</h4>
</div>